package org.g4studio.core.web.report.jasper.applet;

import java.awt.BorderLayout;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.URL;

import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 * EmbeddedViewerApplet
 * 
 * @author XiongChun
 * @since 2010-09-27
 */
public class EmbeddedViewerApplet extends javax.swing.JApplet {

	/**
	 *
	 */
	private JasperPrint jasperPrint = null;

	/** Creates new form AppletViewer */
	public EmbeddedViewerApplet() {
		initComponents();
	}

	/**
	*
	*/
	public void init() {
		String url = getParameter("REPORT_URL");
		if (url != null) {
			try {
				jasperPrint = (JasperPrint) JRLoader.loadObject(new URL(getCodeBase(), url));
				if (jasperPrint != null) {
					JRViewerSimple viewer = new JRViewerSimple(jasperPrint);
					this.pnlMain.add(viewer, BorderLayout.CENTER);
				}
			} catch (Exception e) {
				StringWriter swriter = new StringWriter();
				PrintWriter pwriter = new PrintWriter(swriter);
				e.printStackTrace(pwriter);
				JOptionPane.showMessageDialog(this, swriter.toString());
			}
		} else {
			JOptionPane.showMessageDialog(this, "Source URL not specified");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		pnlMain = new javax.swing.JPanel();

		pnlMain.setLayout(new java.awt.BorderLayout());

		getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

	}// GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel pnlMain;
	// End of variables declaration//GEN-END:variables

}
