spring:
  application:
    name: pangu-admin-system
  profiles:
    active: ${spring.active:dev}
nacos:
  config:
    namespace: ${nacos.namespace:dev}
    server-addr: ${nacos.server-addr:127.0.0.1:8848}
    username: ${nacos.username:nacos}
    password: ${nacos.password:nacos}
    type: yaml
    data-id: ${spring.application.name}.${nacos.config.type}
    auto-refresh: true
    bootstrap:
      enable: true
      log-enable: true